apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  labels:
    app: todo-app
spec:
  rules:
  - host: 192-168-49-2.nip.io
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: todo-front-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: todo-api-service
            port:
              number: 80
        